[package]
name = "dht-hal-drv"
version = "0.1.0"
authors = ["Rumato Estorsky <rumatoest@users.noreply.github.com>"]
edition = "2018"

[dependencies]
# nb = "0.1.2"
embedded-hal = { version = "0.2.2", features = ["unproven"] }
